development:
  adapter: mysql2
  encoding: utf8
  database: mercury_dev
  pool: 5
  username: root
  password: secret
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: mercury_test
  pool: 5
  username: root
  password: secret
  socket: /var/run/mysqld/mysqld.sock

production:
  adapter: mysql2
  encoding: utf8
  database: mercury_db
  pool: 5
  username: root
  password: secret
  socket: /var/run/mysqld/mysqld.sock

